openapi: "3.0.3"
info:
  title: "ktor_clo_exaple API"
  description: "ktor_clo_exaple API"
  version: "1.0.0"
servers:
- url: "https://ktor_clo_exaple"
paths:
  /json/kotlinx-serialization:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"